name: CasaLingua CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, '3.10']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-asyncio pytest-cov black mypy ruff
        
    - name: Create required directories
      run: |
        mkdir -p models/translation models/multipurpose models/verification models/tokenizers
        mkdir -p cache/models cache/api
        mkdir -p data/backups data/documents
        mkdir -p logs/app logs/audit logs/metrics
        mkdir -p temp indexes knowledge_base
        
    - name: Lint with ruff
      run: |
        # Use ruff for faster linting
        ruff check app/
        
    - name: Format check with black
      run: |
        black --check app/
        
    - name: Type check with mypy
      run: |
        mypy app/
        
    - name: Run tests
      run: |
        # Skip tests that require actual models
        pytest -xvs app/tests/unit --cov=app --cov-report=xml
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false