name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '**/*.md'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '**/*.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material pymdown-extensions

    - name: Generate config if missing
      run: |
        if [ ! -f mkdocs.yml ]; then
          cat > mkdocs.yml << EOF
          site_name: CasaLingua Documentation
          site_description: Language Processing & Translation Pipeline
          theme:
            name: material
            palette:
              primary: indigo
              accent: amber
            features:
              - navigation.tabs
              - navigation.sections
              - navigation.expand
              - content.code.copy
          markdown_extensions:
            - pymdownx.highlight
            - pymdownx.superfences
            - pymdownx.inlinehilite
            - pymdownx.tabbed
            - pymdownx.critic
            - pymdownx.tasklist:
                custom_checkbox: true
          nav:
            - Home: 'index.md'
            - Getting Started: 'getting-started.md'
            - Configuration:
              - Overview: 'configuration/README.md'
              - Database: 'configuration/database.md'
            - API:
              - Overview: 'api/README.md'
              - Translation: 'api/translation.md'
              - Simplification: 'api/simplification.md'
              - Language Detection: 'api/language-detection.md'
            - Architecture: 
              - Overview: 'architecture/README.md'
            - Development:
              - Git Structure: 'development/git_structure.md'
          EOF
        fi
        
    - name: Prepare docs directory
      run: |
        # Ensure docs directory is properly set up for mkdocs
        mkdir -p docs
        
        # Create index.md if it doesn't exist
        if [ ! -f docs/index.md ]; then
          cp docs/README.md docs/index.md || echo "# CasaLingua Documentation" > docs/index.md
        fi
        
    - name: Build docs
      run: mkdocs build --verbose
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: site/
        
  deploy-docs:
    needs: build-docs
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions
          
      - name: Download site
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: site
          
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mkdocs gh-deploy --force