name: YAML Lint

on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  yaml-lint:
    name: Lint YAML files
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
          
      - name: Lint workflow files
        run: |
          echo "Linting GitHub Actions workflow files"
          yamllint -c .github/yamllint-config.yml .github/workflows/
          
  actionlint:
    name: Check GitHub Actions syntax
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.6.26
        
      - name: Check workflow files
        run: |
          echo "Checking GitHub Actions workflow files"
          ./actionlint -color -shellcheck=